/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as privateRouteRouteImport } from './routes/(private)/route'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as publicTrocasEDevolucoesRouteImport } from './routes/(public)/trocas-e-devolucoes'
import { Route as publicTermosDeUsoRouteImport } from './routes/(public)/termos-de-uso'
import { Route as publicPoliticasDePrivacidadeRouteImport } from './routes/(public)/politicas-de-privacidade'
import { Route as publicLoginRouteImport } from './routes/(public)/login'
import { Route as publicEntregaEFreteRouteImport } from './routes/(public)/entrega-e-frete'
import { Route as privateProdutosIndexRouteImport } from './routes/(private)/produtos/index'
import { Route as privateCategoriasIndexRouteImport } from './routes/(private)/categorias/index'
import { Route as publicProdutosProductIdRouteImport } from './routes/(public)/produtos.$productId'
import { Route as privateProdutosRegistrarRouteImport } from './routes/(private)/produtos/registrar'
import { Route as privateCategoriasRegistrarRouteImport } from './routes/(private)/categorias/registrar'
import { Route as privateProdutosImagensProductIdRouteImport } from './routes/(private)/produtos/imagens.$productId'
import { Route as privateProdutosEditarProductIdRouteImport } from './routes/(private)/produtos/editar.$productId'
import { Route as privateCategoriasEditarCategoryIdRouteImport } from './routes/(private)/categorias/editar.$categoryId'

const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const privateRouteRoute = privateRouteRouteImport.update({
  id: '/(private)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicTrocasEDevolucoesRoute = publicTrocasEDevolucoesRouteImport.update({
  id: '/trocas-e-devolucoes',
  path: '/trocas-e-devolucoes',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicTermosDeUsoRoute = publicTermosDeUsoRouteImport.update({
  id: '/termos-de-uso',
  path: '/termos-de-uso',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicPoliticasDePrivacidadeRoute =
  publicPoliticasDePrivacidadeRouteImport.update({
    id: '/politicas-de-privacidade',
    path: '/politicas-de-privacidade',
    getParentRoute: () => publicRouteRoute,
  } as any)
const publicLoginRoute = publicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicEntregaEFreteRoute = publicEntregaEFreteRouteImport.update({
  id: '/entrega-e-frete',
  path: '/entrega-e-frete',
  getParentRoute: () => publicRouteRoute,
} as any)
const privateProdutosIndexRoute = privateProdutosIndexRouteImport.update({
  id: '/produtos/',
  path: '/produtos/',
  getParentRoute: () => privateRouteRoute,
} as any)
const privateCategoriasIndexRoute = privateCategoriasIndexRouteImport.update({
  id: '/categorias/',
  path: '/categorias/',
  getParentRoute: () => privateRouteRoute,
} as any)
const publicProdutosProductIdRoute = publicProdutosProductIdRouteImport.update({
  id: '/produtos/$productId',
  path: '/produtos/$productId',
  getParentRoute: () => publicRouteRoute,
} as any)
const privateProdutosRegistrarRoute =
  privateProdutosRegistrarRouteImport.update({
    id: '/produtos/registrar',
    path: '/produtos/registrar',
    getParentRoute: () => privateRouteRoute,
  } as any)
const privateCategoriasRegistrarRoute =
  privateCategoriasRegistrarRouteImport.update({
    id: '/categorias/registrar',
    path: '/categorias/registrar',
    getParentRoute: () => privateRouteRoute,
  } as any)
const privateProdutosImagensProductIdRoute =
  privateProdutosImagensProductIdRouteImport.update({
    id: '/produtos/imagens/$productId',
    path: '/produtos/imagens/$productId',
    getParentRoute: () => privateRouteRoute,
  } as any)
const privateProdutosEditarProductIdRoute =
  privateProdutosEditarProductIdRouteImport.update({
    id: '/produtos/editar/$productId',
    path: '/produtos/editar/$productId',
    getParentRoute: () => privateRouteRoute,
  } as any)
const privateCategoriasEditarCategoryIdRoute =
  privateCategoriasEditarCategoryIdRouteImport.update({
    id: '/categorias/editar/$categoryId',
    path: '/categorias/editar/$categoryId',
    getParentRoute: () => privateRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/entrega-e-frete': typeof publicEntregaEFreteRoute
  '/login': typeof publicLoginRoute
  '/politicas-de-privacidade': typeof publicPoliticasDePrivacidadeRoute
  '/termos-de-uso': typeof publicTermosDeUsoRoute
  '/trocas-e-devolucoes': typeof publicTrocasEDevolucoesRoute
  '/': typeof publicIndexRoute
  '/categorias/registrar': typeof privateCategoriasRegistrarRoute
  '/produtos/registrar': typeof privateProdutosRegistrarRoute
  '/produtos/$productId': typeof publicProdutosProductIdRoute
  '/categorias/': typeof privateCategoriasIndexRoute
  '/produtos/': typeof privateProdutosIndexRoute
  '/categorias/editar/$categoryId': typeof privateCategoriasEditarCategoryIdRoute
  '/produtos/editar/$productId': typeof privateProdutosEditarProductIdRoute
  '/produtos/imagens/$productId': typeof privateProdutosImagensProductIdRoute
}
export interface FileRoutesByTo {
  '/entrega-e-frete': typeof publicEntregaEFreteRoute
  '/login': typeof publicLoginRoute
  '/politicas-de-privacidade': typeof publicPoliticasDePrivacidadeRoute
  '/termos-de-uso': typeof publicTermosDeUsoRoute
  '/trocas-e-devolucoes': typeof publicTrocasEDevolucoesRoute
  '/': typeof publicIndexRoute
  '/categorias/registrar': typeof privateCategoriasRegistrarRoute
  '/produtos/registrar': typeof privateProdutosRegistrarRoute
  '/produtos/$productId': typeof publicProdutosProductIdRoute
  '/categorias': typeof privateCategoriasIndexRoute
  '/produtos': typeof privateProdutosIndexRoute
  '/categorias/editar/$categoryId': typeof privateCategoriasEditarCategoryIdRoute
  '/produtos/editar/$productId': typeof privateProdutosEditarProductIdRoute
  '/produtos/imagens/$productId': typeof privateProdutosImagensProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(private)': typeof privateRouteRouteWithChildren
  '/(public)': typeof publicRouteRouteWithChildren
  '/(public)/entrega-e-frete': typeof publicEntregaEFreteRoute
  '/(public)/login': typeof publicLoginRoute
  '/(public)/politicas-de-privacidade': typeof publicPoliticasDePrivacidadeRoute
  '/(public)/termos-de-uso': typeof publicTermosDeUsoRoute
  '/(public)/trocas-e-devolucoes': typeof publicTrocasEDevolucoesRoute
  '/(public)/': typeof publicIndexRoute
  '/(private)/categorias/registrar': typeof privateCategoriasRegistrarRoute
  '/(private)/produtos/registrar': typeof privateProdutosRegistrarRoute
  '/(public)/produtos/$productId': typeof publicProdutosProductIdRoute
  '/(private)/categorias/': typeof privateCategoriasIndexRoute
  '/(private)/produtos/': typeof privateProdutosIndexRoute
  '/(private)/categorias/editar/$categoryId': typeof privateCategoriasEditarCategoryIdRoute
  '/(private)/produtos/editar/$productId': typeof privateProdutosEditarProductIdRoute
  '/(private)/produtos/imagens/$productId': typeof privateProdutosImagensProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/entrega-e-frete'
    | '/login'
    | '/politicas-de-privacidade'
    | '/termos-de-uso'
    | '/trocas-e-devolucoes'
    | '/'
    | '/categorias/registrar'
    | '/produtos/registrar'
    | '/produtos/$productId'
    | '/categorias/'
    | '/produtos/'
    | '/categorias/editar/$categoryId'
    | '/produtos/editar/$productId'
    | '/produtos/imagens/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/entrega-e-frete'
    | '/login'
    | '/politicas-de-privacidade'
    | '/termos-de-uso'
    | '/trocas-e-devolucoes'
    | '/'
    | '/categorias/registrar'
    | '/produtos/registrar'
    | '/produtos/$productId'
    | '/categorias'
    | '/produtos'
    | '/categorias/editar/$categoryId'
    | '/produtos/editar/$productId'
    | '/produtos/imagens/$productId'
  id:
    | '__root__'
    | '/(private)'
    | '/(public)'
    | '/(public)/entrega-e-frete'
    | '/(public)/login'
    | '/(public)/politicas-de-privacidade'
    | '/(public)/termos-de-uso'
    | '/(public)/trocas-e-devolucoes'
    | '/(public)/'
    | '/(private)/categorias/registrar'
    | '/(private)/produtos/registrar'
    | '/(public)/produtos/$productId'
    | '/(private)/categorias/'
    | '/(private)/produtos/'
    | '/(private)/categorias/editar/$categoryId'
    | '/(private)/produtos/editar/$productId'
    | '/(private)/produtos/imagens/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  privateRouteRoute: typeof privateRouteRouteWithChildren
  publicRouteRoute: typeof publicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)': {
      id: '/(private)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/trocas-e-devolucoes': {
      id: '/(public)/trocas-e-devolucoes'
      path: '/trocas-e-devolucoes'
      fullPath: '/trocas-e-devolucoes'
      preLoaderRoute: typeof publicTrocasEDevolucoesRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/termos-de-uso': {
      id: '/(public)/termos-de-uso'
      path: '/termos-de-uso'
      fullPath: '/termos-de-uso'
      preLoaderRoute: typeof publicTermosDeUsoRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/politicas-de-privacidade': {
      id: '/(public)/politicas-de-privacidade'
      path: '/politicas-de-privacidade'
      fullPath: '/politicas-de-privacidade'
      preLoaderRoute: typeof publicPoliticasDePrivacidadeRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/login': {
      id: '/(public)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof publicLoginRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/entrega-e-frete': {
      id: '/(public)/entrega-e-frete'
      path: '/entrega-e-frete'
      fullPath: '/entrega-e-frete'
      preLoaderRoute: typeof publicEntregaEFreteRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(private)/produtos/': {
      id: '/(private)/produtos/'
      path: '/produtos'
      fullPath: '/produtos/'
      preLoaderRoute: typeof privateProdutosIndexRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/(private)/categorias/': {
      id: '/(private)/categorias/'
      path: '/categorias'
      fullPath: '/categorias/'
      preLoaderRoute: typeof privateCategoriasIndexRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/(public)/produtos/$productId': {
      id: '/(public)/produtos/$productId'
      path: '/produtos/$productId'
      fullPath: '/produtos/$productId'
      preLoaderRoute: typeof publicProdutosProductIdRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(private)/produtos/registrar': {
      id: '/(private)/produtos/registrar'
      path: '/produtos/registrar'
      fullPath: '/produtos/registrar'
      preLoaderRoute: typeof privateProdutosRegistrarRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/(private)/categorias/registrar': {
      id: '/(private)/categorias/registrar'
      path: '/categorias/registrar'
      fullPath: '/categorias/registrar'
      preLoaderRoute: typeof privateCategoriasRegistrarRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/(private)/produtos/imagens/$productId': {
      id: '/(private)/produtos/imagens/$productId'
      path: '/produtos/imagens/$productId'
      fullPath: '/produtos/imagens/$productId'
      preLoaderRoute: typeof privateProdutosImagensProductIdRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/(private)/produtos/editar/$productId': {
      id: '/(private)/produtos/editar/$productId'
      path: '/produtos/editar/$productId'
      fullPath: '/produtos/editar/$productId'
      preLoaderRoute: typeof privateProdutosEditarProductIdRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/(private)/categorias/editar/$categoryId': {
      id: '/(private)/categorias/editar/$categoryId'
      path: '/categorias/editar/$categoryId'
      fullPath: '/categorias/editar/$categoryId'
      preLoaderRoute: typeof privateCategoriasEditarCategoryIdRouteImport
      parentRoute: typeof privateRouteRoute
    }
  }
}

interface privateRouteRouteChildren {
  privateCategoriasRegistrarRoute: typeof privateCategoriasRegistrarRoute
  privateProdutosRegistrarRoute: typeof privateProdutosRegistrarRoute
  privateCategoriasIndexRoute: typeof privateCategoriasIndexRoute
  privateProdutosIndexRoute: typeof privateProdutosIndexRoute
  privateCategoriasEditarCategoryIdRoute: typeof privateCategoriasEditarCategoryIdRoute
  privateProdutosEditarProductIdRoute: typeof privateProdutosEditarProductIdRoute
  privateProdutosImagensProductIdRoute: typeof privateProdutosImagensProductIdRoute
}

const privateRouteRouteChildren: privateRouteRouteChildren = {
  privateCategoriasRegistrarRoute: privateCategoriasRegistrarRoute,
  privateProdutosRegistrarRoute: privateProdutosRegistrarRoute,
  privateCategoriasIndexRoute: privateCategoriasIndexRoute,
  privateProdutosIndexRoute: privateProdutosIndexRoute,
  privateCategoriasEditarCategoryIdRoute:
    privateCategoriasEditarCategoryIdRoute,
  privateProdutosEditarProductIdRoute: privateProdutosEditarProductIdRoute,
  privateProdutosImagensProductIdRoute: privateProdutosImagensProductIdRoute,
}

const privateRouteRouteWithChildren = privateRouteRoute._addFileChildren(
  privateRouteRouteChildren,
)

interface publicRouteRouteChildren {
  publicEntregaEFreteRoute: typeof publicEntregaEFreteRoute
  publicLoginRoute: typeof publicLoginRoute
  publicPoliticasDePrivacidadeRoute: typeof publicPoliticasDePrivacidadeRoute
  publicTermosDeUsoRoute: typeof publicTermosDeUsoRoute
  publicTrocasEDevolucoesRoute: typeof publicTrocasEDevolucoesRoute
  publicIndexRoute: typeof publicIndexRoute
  publicProdutosProductIdRoute: typeof publicProdutosProductIdRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicEntregaEFreteRoute: publicEntregaEFreteRoute,
  publicLoginRoute: publicLoginRoute,
  publicPoliticasDePrivacidadeRoute: publicPoliticasDePrivacidadeRoute,
  publicTermosDeUsoRoute: publicTermosDeUsoRoute,
  publicTrocasEDevolucoesRoute: publicTrocasEDevolucoesRoute,
  publicIndexRoute: publicIndexRoute,
  publicProdutosProductIdRoute: publicProdutosProductIdRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  privateRouteRoute: privateRouteRouteWithChildren,
  publicRouteRoute: publicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
